config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount ActionCable.server => '/cable'

  resources :newsfeeds
  resources :search
  resources :music_choices do
    resources :comments
    resources :suggestions
    resources :likes
    resources :stashed_musics
  end

  resources :stashed_musics

  resources :comments, only: [] do
    resources :likes
  end

  resources :suggestions, only: [] do
    resources :likes
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' }


  resources :users
  resources :likes
  resources :home
  resources :followings

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/notifications" => "mailbox#notifications", as: :mailbox_notifications
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "mailbox/empty_trash" => "mailbox#empty_trash", as: :empty_trash
  get "mailbox/notification_read" => "mailbox#notification_read",
      as: :notification_read
  get "mailbox/notification_all_read" => "mailbox#notification_all_read",
      as: :notification_all_read

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :music_choice
  has_many :likes, dependent: :destroy, as: :likeable

  validates :user_id, presence: true
  validates :body, presence: true, length: { minimum: 3, maximum: 140 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    find_music_choice
    comment_params = params.require(:comment).permit(:body)
    @comment = Comment.new comment_params
    @comment.user = current_user
    @comment.music_choice = @music_choice
    respond_to do |format|
      if @comment.save
        Newsfeed.create(user: current_user,
                        first_user: current_user.username,
                        first_user_id: current_user.id,
                        first_user_image: current_user.image.mail,
                        first_subject: @comment.body,
                        first_subject_id: @comment.id,
                        second_user: @comment.music_choice.user.username,
                        second_user_id: @comment.music_choice.user.id,
                        second_subject_id: @comment.music_choice.id,
                        posttype: 'comment')
                        send_music_notification
        format.js { render :create_comment_success }
        format.html { redirect_to music_choice_path(@music_choice), notice: 'Comment created!' }
      else
        format.js { render :create_comment_failure }
        format.html { redirect_to music_choice_path(@music_choice), alert: "#{@comment.errors.full_messages.join('')}" }
      end
    end
  end

  def destroy
    find_music_choice
    @comment = Comment.find params[:id]
    respond_to do |format|
      if can? :delete, @comment
        @comment.destroy
        format.js {render}
        format.html { redirect_to @music_choice, notice: 'Comment deleted!'}
      else
        format.js {render js: 'alert:("Access denied");' }
        format.html { redirect_to music_choice_path, alert: 'Access Denied' }
      end
    end
  end

  private

  def send_music_notification
    (@music_choice.user).notify(@music_choice.user.username,
    "#{current_user.username} commented on your post of
    #{get_music_name(@music_choice)}", current_user)
  end

  def find_music_choice
    @music_choice = MusicChoice.find params[:music_choice_id]
  end

end

app/views/comments/_comment.html.erb
<div class = "comment" id ="<%= dom_id(comment)%>">
   <%= display_image_mail(comment.user) %>
   <%= link_to comment.user.username, user_path(comment.user) %>:
   <strong>"<%= "#{comment.body} "%>"</strong>
   <% if can? :like, comment %>
     <% @comment_like = comment.like_for(current_user) %>
     <% if @comment_like.present?  %>
       <%= link_to comment_like_path(comment, @comment_like), method: :delete do %>
         <i class="fa fa-check-square" aria-hidden="true"></i>
       <% end %>
     <% else %>
       <%= link_to comment_likes_path(comment), method: :post do %>
         <i class="fa fa-check-square-o" aria-hidden="true"></i>
       <% end %>
     <% end %>
   <% end %>
   <% if can? :delete, comment %>
     <%= link_to music_choice_comment_path(comment.music_choice, comment), method: :delete, remote: true,
                                               data: {confirm: 'Are you sure?'} do %>
       <i class="fa fa-times" aria-hidden="true"></i> <br />
     <% end %>
 </div>
 <% end %>

app/views/comments/_form.html.erb
<div id='likebutton'>
  <%= render '/music_choices/likebutton' %>
</div>
<% if can? :suggestion, @music_choice %>
  <span class='tooltips'title='Make a Suggestion' data-toggle='tooltip' placement= 'top' }>
    <%= button_to new_search_path({type: 'suggestion',
                                  choice_id: @music_choice.id}),
                                  method: :get,
                                  remote: true,
                                  data: { toggle: "modal",
                                  target: "#myModal" } do %>
      <i class="fa fa-bullhorn" aria-hidden="true"></i>
    <% end %>
  </span>
<% end %>
<div id='stashbutton'>
  <%= render '/stashed_musics/stashbutton' %>
</div>
<%= form_for [@music_choice, @comment], remote: true do |c| %>
  <% if @music_choice.user == current_user %>
    <%= c.text_area :body, id: 'longtext' %>
  <% else %>
    <%= c.text_area :body, id: 'shorttext' %>
  <% end %>
    <%= button_tag id: 'commentbutton',
                   class: 'tooltips',
                   title: 'Comment',
                   data: { toggle: 'tooltip',
                   placement: 'top' } do %>
      <i class="fa fa-commenting-o" aria-hidden="true"></i>
    <% end %>
  <% end %>
  <% if can? :modify, @music_choice %>
      <%= button_to music_choice_path(@music_choice),
                                      class: 'tooltips',
                                      title: 'Delete this Post',
                                      data: { toggle: 'tooltip',
                                      placement: 'top',
                                      confirm: 'Are you sure?' },
                                      method: :delete do %>
        <i class="fa fa-trash" aria-hidden="true"></i>
      <% end %>
  <% end %>

app/views/comments/create_comment_failure.js.erb
$('#longtext').val('');
$('#shorttext').val('');

app/views/comments/create_comment_success.js.erb
$('#longtext').val('');
$('#shorttext').val('');
$('#comments').append('<%= j render 'comments/comment', comment: @comment %>');
<% @comment = Comment.new %>

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").hide(400, function(){$(this).remove();});