config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount ActionCable.server => '/cable'

  resources :newsfeeds
  resources :search
  resources :music_choices do
    resources :comments
    resources :suggestions
    resources :likes
    resources :stashed_musics
  end

  resources :stashed_musics

  resources :comments, only: [] do
    resources :likes
  end

  resources :suggestions, only: [] do
    resources :likes
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' }


  resources :users
  resources :likes
  resources :home
  resources :followings

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/notifications" => "mailbox#notifications", as: :mailbox_notifications
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "mailbox/empty_trash" => "mailbox#empty_trash", as: :empty_trash
  get "mailbox/notification_read" => "mailbox#notification_read",
      as: :notification_read
  get "mailbox/notification_all_read" => "mailbox#notification_all_read",
      as: :notification_all_read

end

app/models/user.rb
class User < ApplicationRecord

  acts_as_messageable

  has_many :music_choices, dependent: :destroy
  has_many :followings, dependent: :destroy
  has_many :followers, through: :followings
  has_many :stalkings, foreign_key: :follower_id, class_name: 'Following'
  has_many :followed_users, through: :stalkings, source: :user
  has_many :comments, dependent: :nullify
  has_many :suggestions, dependent: :nullify
  has_many :likes, dependent: :destroy
  has_many :newsfeeds, dependent: :destroy
  has_many :stashed_musics, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable, :omniauthable, :omniauth_providers => [:spotify]

  validates :username, uniqueness: {case_sensitive: false }, length: { minimum: 3, maximum: 10 }

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.skip_confirmation!
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.image = auth.info.image
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.search(search)
    if search
      self.where('username ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?',
       "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)
    self.email
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]

  def index
    @following = Following.new
    @users = User.search(params[:search]).order(created_at: :desc)
  end

  def show
    find_user
    top_marks(@user)
    @following = Following.new
    @music_choices = MusicChoice.order(created_at: :desc).page(params[:page]).
                                 where(:user_id => @user.id).per(9)
  end

  private

  def find_user
    @user ||= User.find params[:id]
  end

  def top_marks(user)
    if user.music_choices.count > 0
      @top_artist = user.music_choices.group(:artist).order('count_id DESC').count(:id).first[0]
    else
      @top_artist = 'n/a'
    end
    if user.suggestions.count > 0
      @top_suggestion = user.suggestions.group([:artist, :album, :track]).
                        order('count_id DESC').count(:id).first[0].join(', ')
    else
      @top_suggestion = 'n/a'
    end
  end

end

app/views/users/_followers.html.erb
<div id='users-followers-view' class="collapse collapsible-list-toggle">

  <div style='text-align: center; margin: 5px;'>
    <a class="btn btn-success users-album-view-link">Back</a>
  </div>

  <% if @user == current_user %>
    <br /> <% @user.followers.each do |user| %>
    <% top_marks(user) %>
    <div class ='user-show'>
      <div class='user-info'>
        <%= link_to user_path(user) do %>
          <%= display_image(user) %>
        <% end %>
        <div class='user-text' style='margin-top: 7px;'>
          Username: <%= user.username %> <br />
          Joined: <%= user.created_at.strftime("%d %b. %Y")%>  <br />
          Reputation: <%= user.reputation %> <br />
          Posts: <%= user.music_choices.count %> <br />
          Most Frequently Recommended: <%= @top_suggestion %><br />
          Most Frequently Posted Artist: <%= @top_artist %><br />
        </div>
        <% if can? :follow, user %>
          <% if (current_user.followed_users.ids).include? user.id %>
            <% @follow = (Following.where("user_id = ? AND follower_id = ?", user,
                                           current_user).first.id)%>
            <%= button_to 'Unfollow', following_path(@follow), class: 'btn btn-success',
                                                               method: :delete,
                                                               data: { confirm: 'Are you sure?' } %>
          <% else %>

            <%= form_for @following do |f| %>
              <%= hidden_field_tag :user_id, user.id %>
              <%= f.submit 'Follow', class: 'btn btn-success', id: 'follow_button' %>
            <% end %>

          <% end %>
        <% end %>
      </div>
    </div>
   <% end %> <br />
  <% end %>

</div>

app/views/users/_following.html.erb
<div id='users-following-view' class="collapse collapsible-list-toggle">

  <div style='text-align: center; margin: 5px;'>
    <a class="btn btn-success users-album-view-link">Back</a>
  </div>

  <% if @user == current_user %>
    <br /> <% @user.followed_users.each do |user| %>
    <% top_marks(user) %>
    <div class ='user-show'>
      <div class='user-info'>
        <%= link_to user_path(user) do %>
          <%= display_image(user) %>
        <% end %>
        <div class='user-text' style='margin-top: 7px;'>
          Username: <%= user.username %> <br />
          Joined: <%= user.created_at.strftime("%d %b. %Y")%>  <br />
          Reputation: <%= user.reputation %> <br />
          Posts: <%= user.music_choices.count %> <br />
          Most Frequently Recommended: <%= @top_suggestion %><br />
          Most Frequently Posted Artist: <%= @top_artist %><br />
        </div>
        <% if can? :follow, user %>
          <% if (current_user.followed_users.ids).include? user.id %>
            <% @follow = (Following.where("user_id = ? AND follower_id = ?", user,
                                           current_user).first.id)%>
            <%= button_to 'Unfollow', following_path(@follow), class: 'btn btn-success',
                                                               method: :delete,
                                                               data: { confirm: 'Are you sure?' } %>
          <% else %>

            <%= form_for @following do |f| %>
              <%= hidden_field_tag :user_id, user.id %>
              <%= f.submit 'Follow', class: 'btn btn-success', id: 'follow_button' %>
            <% end %>

          <% end %>
        <% end %>
      </div>
    </div>
               <% end %> <br />
  <% end %>

</div>

app/views/users/_users_album_view.html.erb
<div id='users-album-view' class="collapsible-list-toggle">

  <% if !can? :follow, @user %>
    <div style='text-align: center; margin: 5px; margin-bottom:15px;'>
      <a class="btn btn-success users-followers-link">Followers</a>
      <a class="btn btn-success users-following-link">Following</a>
    </div>
  <% end %>


  <% @music_choices = Kaminari.paginate_array(@music_choices).page(params[:page]).per(9) %>
    <div class='musicpage'>
      <% @music_choices.each do |m| %>
        <figure style="width: 300px; height: 300px; float: left; margin-right: 20px; margin-bottom:40px;">
          <%=link_to image_tag("#{m.album_art}"), music_choice_path(m.id)%>
          <figcaption><p>
             <%= m.artist %>  <br /> <%= m.album %> <br /> <%= m.track %>
          </p></figcaption>
          <div class=username style='font-size: 25px; color: #6B9430;'>
            <% if can? :like, m %>
              <% @music_choice_like = m.like_for(current_user) %>
              <% if @music_choice_like.present? %>
                <%= link_to music_choice_like_path(m, @music_choice_like), method: :delete do %>
                <i class="fa fa-check-square" aria-hidden="true"></i>
                <% end %>
              <% else %>
                <%= link_to music_choice_likes_path(m), method: :post do %>
                <i class="fa fa-check-square-o" aria-hidden="true"></i>
                <% end %>
              <% end %>
            <% end %>
            <% if can? :stashed_music, m %>
              <%= link_to music_choice_stashed_musics_path(m), method: :post do %>
                <i class="fa fa-archive" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </figure>
      <% end %>
    </div>
    <div class='user-pagination'>
      <%= paginate @music_choices %>
    </div>

</div>

app/views/users/index.html.erb
<h1 style='margin-left: 120px;'>Users matching: <%= (params[:search]) %></h1> <br />


<% if @users %>
  <% @users = Kaminari.paginate_array(@users).page(params[:page]).per(9) %>
  <% @users.each do |user| %>
    <% top_marks(user) %>
    <div class ='user-show'>
      <div class='user-info'>
        <%= link_to user_path(user) do %>
        <%= display_image(user) %>
        <% end %>
        <div class='user-text' style='margin-top: 7px;'>
          Username: <%= user.username %> <br />
          Joined: <%= user.created_at.strftime("%d %b. %Y")%>  <br />
          Reputation: <%= user.reputation %> <br />
          Posts: <%= user.music_choices.count %> <br />
          Most Frequently Recommended: <%= @top_suggestion %><br />
          Most Frequently Posted Artist: <%= @top_artist %><br />
        </div>
        <% if can? :follow, user %>
          <% if (current_user.followed_users.ids).include? user.id %>
            <% @follow = (Following.where("user_id = ? AND follower_id = ?", user,
                                           current_user).first.id)%>
            <%= button_to 'Unfollow', following_path(@follow), class: 'btn btn-success',
                                                               method: :delete,
                                                               data: { confirm: 'Are you sure?' } %>
          <% else %>
            <div class='form-container'>
            <%= form_for @following do |f| %>
              <%= hidden_field_tag :user_id, user.id %>
              <%= f.submit 'Follow', class: 'btn btn-success' %>
            <% end %>
            </div>
          <% end %>
        <% end %>

      </div>
    </div>
  <% end %>
  <div class='user-pagination'>
    <%= paginate @users %>
  </div>
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? %>

  <div class ='user-show'>
    <div class='user-info'>
      <%= display_image(@user) %>
      <div class='user-text' >
        <% top_marks(@user) %>
        Username: <%= @user.username %> <br />
        Joined: <%= @user.created_at.strftime("%d %b. %Y")%>  <br />
        Reputation: <%= @user.reputation %> <br />
        Posts: <%= @user.music_choices.count %> <br />
        Most Frequently Recommended: <%= @top_suggestion %><br />
        Most Frequently Posted Artist: <%= @top_artist %><br />
      </div>
      <% if can? :follow, @user %>
        <% if (current_user.followed_users.ids).include? @user.id %>
          <% @follow = (Following.where("user_id = ? AND follower_id = ?", @user,
                                         current_user).first.id)%>
          <%= button_to 'Unfollow', following_path(@follow), class: 'btn btn-success',
                                                             method: :delete,
                                                             data: { confirm: 'Are you sure?' } %>
        <% else %>
          <div class='form-container'>
          <%= form_for @following do |f| %>
            <%= hidden_field_tag :user_id, @user.id %>
            <%= f.submit 'Follow', class: 'btn btn-success' %>
          <% end %>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>

  <div class='users-view'>
    <%= render partial: 'users/users_album_view' %>
    <%= render partial: 'users/followers' %>
    <%= render partial: 'users/following' %>
  </div>

<% end %>