config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount ActionCable.server => '/cable'

  resources :newsfeeds
  resources :search
  resources :music_choices do
    resources :comments
    resources :suggestions
    resources :likes
    resources :stashed_musics
  end

  resources :stashed_musics

  resources :comments, only: [] do
    resources :likes
  end

  resources :suggestions, only: [] do
    resources :likes
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' }


  resources :users
  resources :likes
  resources :home
  resources :followings

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/notifications" => "mailbox#notifications", as: :mailbox_notifications
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "mailbox/empty_trash" => "mailbox#empty_trash", as: :empty_trash
  get "mailbox/notification_read" => "mailbox#notification_read",
      as: :notification_read
  get "mailbox/notification_all_read" => "mailbox#notification_all_read",
      as: :notification_all_read

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      @music_choices = (MusicChoice.order(created_at: :desc).
                        page(params[:page]).
                        where(:user_id => current_user.followed_users)
                        .or(MusicChoice.order(created_at: :desc).
                        page(params[:page]).where(:user_id => current_user))).
                        page(params[:page]).per(8)
      @combined_news = (Newsfeed.order(created_at: :desc).
                        page(params[:page]).
                        where(:user_id => current_user.followed_users)
                       .or(Newsfeed.order(created_at: :desc).
                        page(params[:page]).where(:user_id => current_user))).
                        page(params[:page]).per(21)
    end
    respond_to do |format|
      format.html {render}
      format.js {render 'music_choices'}
    end
  end

  def show
    @music_choice ||= MusicChoice.find params[:id]
    @comment ||= Comment.new
    @combined = (@music_choice.suggestions + @music_choice.comments).
                sort_by {|record| record.created_at}.reverse!
  end

end

app/views/home/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document" style='width: 630px'>
    <div class="modal-content">
      <div class='modal-body'>
      </div>
    </div>
  </div>
</div>

app/views/home/_music_choices.html.erb
<div class='album-layout'>
  <% @music_choices.each do |m| %>
    <figure style="width: 300px; height: 300px; float: left; margin-right: 20px; margin-bottom: 80px;">
       <%=link_to image_tag("#{m.album_art}"), music_choice_path(m.id)%>
       <figcaption>
         <p>
           <%= m.artist %>  <br /> <%= m.album %> <br /> <%= m.track %>
         </p>
       </figcaption>
       <figname>
         <%= display_image_mail(m.user) %>
         <%= link_to m.user.username, user_path(m.user.id) %>
       </figname>
       <figbuttons>
         <% if can? :like, m %>
           <% @music_choice_like = m.like_for(current_user) %>
           <% if @music_choice_like.present? %>
             <%= link_to music_choice_like_path(m, @music_choice_like), method: :delete do %>
             <i class="fa fa-check-square" aria-hidden="true"></i>
             <% end %>
           <% else %>
             <%= link_to music_choice_likes_path(m), method: :post do %>
             <i class="fa fa-check-square-o" aria-hidden="true"></i>
             <% end %>
           <% end %>
         <% end %>
         <% if can? :stashed_music, m %>
           <% @music_choice_stash = m.stashed_for(current_user) %>
           <% if !@music_choice_stash.present? %>
             <%= link_to music_choice_stashed_musics_path(m), method: :post do %>
               <i class="fa fa-folder-open-o" " aria-hidden="true"></i>
             <% end %>
           <% else %>
           <%= link_to music_choice_stashed_music_path(m, m.stashed_for(current_user)),
                                                         method: :delete do %>
             <i class="fa fa-folder-open" aria-hidden="true"></i>
             <% end %>
           <% end %>
          <% end %>
       </figbuttons>
     </figure>
   <% end %>
 </div>

app/views/home/_sign_in.html.erb
<div class='wallpaper'>
  <div class='black-opacity'>
    <div id='welcome-input'>
      <h1>WELCOME TO SPLITTER</h1>
      <h3>Sign in or register to get started.</h3>
      <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary btn-lg' %>
      <%= link_to 'Sign in with Spotify', user_spotify_omniauth_authorize_path, class: 'btn btn-success btn-lg' %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class='main-view'>
  <br />
  <br />

  <% if user_signed_in? && (current_user.music_choices.count > 0 || current_user.followed_users.count > 0) %>

    <div class='album-news' style='display: flex;'>

      <div class='music-table col-md-9'>
        <table>
          <%= render :partial => 'music_choices', :object => @music_choices %>
        </table>
        <p class="musicpagination">
          <%= link_to_next_page(@music_choices, 'Next Page', remote: true) %>
        </p>
      </div>

      <div class='news-box news-table col-md-3' style='margin-right: 40px;'>
        <div id="combined_news"> <%= render @combined_news %> </div>
          <p class="newspagination">
            <%= link_to_next_page(@combined_news, 'Next Page') %>
          </p>
      </div>

    </div>

  <% elsif user_signed_in? && current_user.music_choices.count == 0 %>
    <h1 style='font-weight: bold; margin-top:100px; text-align: center;'>
      Nothing to see yet. Post some music or follow a friend to get started.</h1>
  <% else %>
    <%= render partial: 'sign_in' %>
  <% end %>

app/views/home/music_choices.js.erb
$("<%=j render(:partial => 'music_choices', :object => @music_choices) %>")
  .appendTo($(".music-table table"));

$("<%=j render(:partial => 'newsfeeds/newsfeed_append', :object => @combined_news) %>")
  .appendTo($(".news-table"));

<% if @music_choices.last_page? %>
  $('.musicpagination').html('');
<% else %>
  $('.musicpagination')
    .html("<%=j link_to_next_page(@music_choices, 'Next Page', :remote => true) %>");
<% end %>