config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  mount ActionCable.server => '/cable'

  resources :newsfeeds
  resources :search
  resources :music_choices do
    resources :comments
    resources :suggestions
    resources :likes
    resources :stashed_musics
  end

  resources :stashed_musics

  resources :comments, only: [] do
    resources :likes
  end

  resources :suggestions, only: [] do
    resources :likes
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' }


  resources :users
  resources :likes
  resources :home
  resources :followings

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/notifications" => "mailbox#notifications", as: :mailbox_notifications
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "mailbox/empty_trash" => "mailbox#empty_trash", as: :empty_trash
  get "mailbox/notification_read" => "mailbox#notification_read",
      as: :notification_read
  get "mailbox/notification_all_read" => "mailbox#notification_all_read",
      as: :notification_all_read

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listen</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-bottom: 100px;">

    <%= render partial: 'home/modal' %>
    <%= render partial: 'suggestions/suggestion_modal' %>

    <nav class="navbar navbar-inverse">
      <div class="container">

        <div class="navbar-header" style='color: white; font-size: 20px;'>
          <button type="button"
                  class="navbar-toggle collapsed"
                  data-toggle="collapse"
                  data-target="#my-navbar">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </button>
        </div>

        <div class="navbar-header">
          <%= link_to root_path do%>
            <%=image_tag 'split-icon.png', style: 'height:40px; margin-top: 10px; margin-right: 10px;' %>
          <% end %>
        </div>

        <div class="navbar-header">
          <%= link_to 'Splitter [demo]', root_path, class: 'navbar-brand' %>
        </div>

        <div id="navbar">
          <div class="navbar-collapse collapse" id="my-navbar">
            <ul class= 'nav navbar-nav' style='margin-left: 220px;'>
              <li>
                <%= form_tag(users_path, method: 'get', class: 'navbar-form navbar-left') do %>
                <%= search_field_tag 'search', nil, class: 'form-control', placeholder: 'User Search'  %>
                <%= button_tag(type: "submit", class: "btn btn-inverse", :name => nil) do %>
                  <i class="fa fa-search" aria-hidden="true"></i>
                <% end %>
                <% end %>
              </li>
            </ul>
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li>
                <%=link_to music_choices_path do %>
                  <i class="fa fa-users" aria-hidden="true"></i>
                <% end %>
              </li>
              <li>
                <% if unread_count > 0 %>
                  <span class="label label-danger" style='position: absolute; margin-top: 32px; margin-left: 7px; z-index: 3;'><%=unread_count%></span>
                <% end %>
                <%=link_to mailbox_notifications_path do %>
                  <i class="fa fa-envelope" aria-hidden="true"></i>
                <% end %>
              </li>
              <li>
              <%=link_to stashed_musics_path do %>
                <i class="fa fa-archive" aria-hidden="true"></i>
              <% end %>
              </li>
              <li><%= link_to new_search_path({type: 'music_choice'}),
                                                          method: :get,
                                                          class: 'music-choice',
                                                          remote: true,
                                                          data: { toggle: "modal",
                                                                  target: "#myModal" } do %>
                    <i class="fa fa-music" aria-hidden="true"></i>
                  <% end %>
              </li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.username %>
                <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', user_path("#{current_user.id}") %></li>
                  <li><%= link_to 'Edit Settings', edit_user_registration_path %></li>
                  <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
                </ul>
                </li>
            <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
      </div>
    </nav>

    <footer class="navbar navbar-fixed-bottom navbar-inverse" style='height: 20px;'>
    </footer>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" data-dismiss="alert">
          <%= value %>
        </div>
      <% end %>
    </div>

    <%= yield :top_content %>

    <div class="container">
      <h1><%= yield :header %></h1>
      <%= yield %>
    </div>

  </body>
</html>